#회원가입
POST http://127.0.0.1:5001/userProc
Content-Type: application/json

{
"username" : "test",
"password" : "q1w2e3r4",
"email" : "test@exam.com"
}

######################################
#사용자 로그인
POST http://127.0.0.1:5001/login
Content-Type: application/json

{
    "username": "test",
    "password": "q1w2e3r4"
}

#####################################
#스레스 생성
POST http://127.0.0.1:5001/threads
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3NTY4MzI3OTl9.aYZ94RXiXCI8x_WvKm-r6u9laef10jMvxv1DxaxqVAo

{
    "title": "테스트 스레드"
}
######################################
#스레드 조회
GET http://127.0.0.1:5001/threads/1