"""Migrate First all table

Revision ID: 0c59a976b799
Revises: 
Create Date: 2025-09-30 16:02:45.241778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c59a976b799'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('ip',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('ip',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=45),
               existing_nullable=False)

    # ### end Alembic commands ###
